In [16]:

from locale import normalize

import numpy as np

data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])

# Calculate the mean temperature for each day
mean_temperatures = np.mean(data, axis=1)
print("Shape of the data array:", data.shape)
print("Mean temperatures for each day:", mean_temperatures)

high_temperatures = data[data > 28.0]
high_temp=high_temperatures.flatten()
print("Indices of temperatures above 28 degrees:", high_temp)

normalized_data = (data - data.min()) / (data.max() - data.min())
print("Normalized data:\n", np.round(normalized_data, 2))

Shape of the data array: (4, 5)
Mean temperatures for each day: [25.3  23.78 26.58 25.26]
Indices of temperatures above 28 degrees: [31.2 28.7 30.5 33.1 29.6 31.9 28.1]
Normalized data:
 [[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
